### ISSUE TITLE
拓展psram

### ISSUE THREAD

**Issue by ABeautifulChicken** [Forairaaaaa/Rachel#4]
大佬，我发现乐鑫官方店里有一个esp32s3-PICO芯片，集成了晶振和N8R8，管脚兼容传统的esp32s3芯片，所以只需要把原来的m5stamp上面的芯片吹下来，换上这个芯片，在pio.ini里面选择8Mpsram，应该就能同时使用WiFi图传和其他功能了吧？

**Comment by Forairaaaaa** [comment]
理论可行，不过pio的设置我没试过~
