### ISSUE TITLE
工程编译报错:no matching function for call to 'LGFX_SpriteFx::loadFont(const char [24], fs::SDFS&)'

### ISSUE THREAD

**Issue by winerxu** [Forairaaaaa/Rachel#7]
错误提示：
src/rachel/hal/hal_rachel/components/hal_sdcard.cpp:40:63: error: no matching function for call to 'LGFX_SpriteFx::loadFont(const char [24], fs::SDFS&)'

截图：
<img width="728" alt="75A0DCF5-EF8A-46c8-993B-1E0725B05DC3" src="https://github.com/Forairaaaaa/Rachel/assets/36878772/4ebf981e-b4dc-40b9-94c1-d7a4d0469961">

log文件：[LOG.txt](https://github.com/Forairaaaaa/Rachel/files/14508272/LOG.txt)

交作业失败啦！请大佬帮忙！

**Comment by Forairaaaaa** [comment]
🫠

**Comment by Forairaaaaa** [comment]
再试试~

**Comment by Forairaaaaa** [comment]
最新主线

**Comment by winerxu** [comment]
不是那个报错了。
又遇到了其他问题。像是环境的。
.platformio/packages/framework-arduinoespressif32/cores/esp32/binary.h:31:12: error: expected'>’ before numeric constant

![微信图片_20240307102254](https://github.com/Forairaaaaa/Rachel/assets/36878772/3a4f19a1-e05d-46ff-93ff-068677bded24)

**Comment by winerxu** [comment]
[LOG2.txt](https://github.com/Forairaaaaa/Rachel/files/14517925/LOG2.txt)
附上日志

**Comment by winerxu** [comment]
哈哈，解决啦，还是没有编最新的版本， 我拉的是你发表情和“再试试”之间时间的版本，后来又编了“再试试”之后的版本。
交作业！
![微信截图_20240307105549](https://github.com/Forairaaaaa/Rachel/assets/36878772/bf33c66e-acc4-48e1-aa3c-54e9f10ac614)

**Comment by Forairaaaaa** [comment]
感谢测试~看来format脚本没毛病

**Comment by wheniseeyouagain** [comment]
我用最新的版本编译也是报这个错，该怎么解决？
