### ISSUE TITLE
无法成功读取NES的ROM

### ISSUE THREAD

**Issue by winerxu** [Forairaaaaa/Rachel#8]
系统启动界面正常，设置正常，raylib games正常，进入NES游戏可以看到SD卡的list，但是再启动时，一直停留在读取ROM的界面，进度条一直处于快速重复加载（没有卡死，刷新速度特别快）的情况。

![微信截图_20240307113556](https://github.com/Forairaaaaa/Rachel/assets/36878772/786a4def-ad88-4df3-95ef-3bf6f9a34709)
![微信截图_20240307113606](https://github.com/Forairaaaaa/Rachel/assets/36878772/c53f83f3-beab-453d-be0c-5a1307431211)

**Comment by Forairaaaaa** [comment]
是不是sd卡没初始化成功

**Comment by winerxu** [comment]
我是没有 ”SD卡初始化“这个动作的，就是自己格式化了一下，手动创建目录，下载ROM。

**Comment by winerxu** [comment]
开机启动LOG  上全是 绿色  通过的

**Comment by winerxu** [comment]
en, 好像是SD卡里我没有创建字体文件夹，也没有找到font_text_24.vlw这个字体。
跳转到[Zpix](https://github.com/SolidZORO/zpix-pixel-font)里也没有找到。。。

**Comment by winerxu** [comment]
是我的错，我换了个SD卡就好了。那个破卡有问题。
![微信截图_20240307165952](https://github.com/Forairaaaaa/Rachel/assets/36878772/add395d5-007c-4a80-9683-b0035080cb01)
